package addressbook.app.com.addressbook.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import addressbook.app.com.addressbook.greendao.db.AddressBook;

import addressbook.app.com.addressbook.greendao.db.AddressBookDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig addressBookDaoConfig;

    private final AddressBookDao addressBookDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        addressBookDaoConfig = daoConfigMap.get(AddressBookDao.class).clone();
        addressBookDaoConfig.initIdentityScope(type);

        addressBookDao = new AddressBookDao(addressBookDaoConfig, this);

        registerDao(AddressBook.class, addressBookDao);
    }
    
    public void clear() {
        addressBookDaoConfig.clearIdentityScope();
    }

    public AddressBookDao getAddressBookDao() {
        return addressBookDao;
    }

}
